ALTER TABLE "Budget" ADD COLUMN "title" TEXT NOT NULL DEFAULT 'My Budget';
ALTER TABLE "Budget" ADD COLUMN "saveAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Budget" ADD COLUMN "spendAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Budget" ADD COLUMN "shareAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
